kind: Deployment
apiVersion: apps/v1
metadata:
  name: icecream-app
  namespace: default
  labels:
    app: icecream-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecream-app
  template:
    metadata:
      labels:
        app: icecream-app
    spec:
      containers:
        - name: eddie-test-repo
          image: eddie55/eddie-test-repo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /opt/app/configs
      volumes:
        - name: config
          secret:
            secretName: icecream-config
            items:
              - key: config
                path: configDB.json
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
